PolicyWebsite/Models/AddPolicy.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace Website.PolicyWebsite.Models
{
    public class AddPolicy
    {
        public AddPolicy()
        {
        }

        public AddPolicy(IEnumerable<BuildingType> constructionTypes)
        {
            this.RiskConstruction = constructionTypes.Select(
                c => new SelectListItem { Text = c.Name, Value = c.Id });
        }

        [Display(Name = "Policy Number")]
        public string PolicyNumber { get; set; }

        [Display(Name = "Effective Date")]
        public string EffectiveDate { get; set; }

        [Display(Name = "Expiration Date")]
        public string ExpireDate { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Street Address")]
        public string Street { get; set; }

        [Display(Name = "City")]
        public string City { get; set; }

        [Display(Name = "City")]
        public string State { get; set; }

        [Display(Name = "Zip")]
        [DataType(DataType.PostalCode)]
        public string Zip { get; set; }

        public string SelectedRiskConstruction { get; set; }

        [Display(Name = "Risk Construction")]
        public IEnumerable<SelectListItem> RiskConstruction { get; set; }

        [Display(Name = "Year Built")]
        public string YearBuilt { get; set; }

        [Display(Name = "Street Address")]
        public string BuildingStreet { get; set; }

        [Display(Name = "City")]
        public string BuildingCity { get; set; }

        [Display(Name = "State")]
        public string BuildingState { get; set; }

        [Display(Name = "Zip")]
        [DataType(DataType.PostalCode)]
        public string BuildingZip { get; set; }
    }
}

PolicyWebsite/Models/Address.cs
using System.ComponentModel.DataAnnotations;

namespace Website.PolicyWebsite.Models
{
    public class Address
    {
        [Required]
        public string Street { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string State { get; set; }

        [Required]
        public string ZipCode { get; set; }
    }
}

PolicyWebsite/Models/BuildingType.cs
namespace Website.PolicyWebsite.Models
{
    public class BuildingType
    {
        public string Name { get; set; }
        
        public string Id { get; set; }
    }
}

PolicyWebsite/Models/DisplayPolicy.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Website.PolicyWebsite.Models
{
    public class DisplayPolicy
    {
        [Display(Name = "Policy Number")]
        public int PolicyNumber { get; set; }

        [Display(Name = "Insured Name")]
        public string InsuredName {
            get
            {
                return $"{this.PrimaryInsuredFirstName} {this.PrimaryInsuredLastName}";
            }
        }

        [Display(Name = "Effective Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime EffectiveDate { get; set; }

        [Display(Name = "Expiration Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime Expiration { get; set; }

        public string PrimaryInsuredFirstName { get; set; }

        public string PrimaryInsuredLastName { get; set; }
    }
}

PolicyWebsite/Models/InsurancePolicy.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Website.PolicyWebsite.Models
{
    public class InsurancePolicy
    {
        [Required]
        public string PolicyNumber { get; set; }

        public DateTime EffectiveDate { get; set; }

        public DateTime Expiration { get; set; }

        [Required]
        public PrimaryInsured PrimaryInsured { get; set; }

        [Required]
        public InsuredRisk InsuredRisk { get; set; }
    }
}

PolicyWebsite/Models/InsuredRisk.cs
using System.ComponentModel.DataAnnotations;

namespace Website.PolicyWebsite.Models
{
    public class InsuredRisk
    {
        [Required]
        public BuildingType ConstructionType { get; set; }

        [Required]
        public string YearBuilt { get; set; }

        [Required]
        public Address Location { get; set; }
    }
}

PolicyWebsite/Models/PrimaryInsured.cs
using System.ComponentModel.DataAnnotations;

namespace Website.PolicyWebsite.Models
{
    public class PrimaryInsured
    {
        [Required]
        public string PrimaryInsuredFirstName { get; set; }

        public string PrimaryInsuredMiddleName { get; set; }

        [Required]
        public string PrimaryInsuredLastName { get; set; }

        [Required]
        public Address PrimaryInsuredAddress { get; set; }
    }
}

PolicyWebsite/Controllers/InsurancePolicyController.cs
using Website.PolicyWebsite.Client;
using Website.PolicyWebsite.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Website.PolicyWebsite.Controllers
{
    public class InsurancePolicyController : Controller
    {
        public InsurancePolicyController(IPolicyServiceClient httpClient)
        {
            this.PolicyServiceClient = httpClient;
        }

        private IPolicyServiceClient PolicyServiceClient { get; }

        public async Task<ActionResult> Index()
        {
            var policies = await this.PolicyServiceClient.FetchAll();
            return View(policies);
        }

        public async Task<PartialViewResult> Add()
        {
            var constructionTypes = await this.PolicyServiceClient.GetConstructionTypes();
            return PartialView("Partial/_AddPolicy", new AddPolicy(constructionTypes));
        }

        [HttpPost]
        public async Task<string> Add(AddPolicy addPolicy)
        {
            return await this.PolicyServiceClient.Save(addPolicy);
        }
    }
}

PolicyWebsite/Views/InsurancePolicy/Index.cshtml
@model IEnumerable<Website.PolicyWebsite.Models.DisplayPolicy>

@section Scripts
{
    <script src="@Url.Content("~/Scripts/modal.js")"></script>
}

<div class="row form-group">
    <div class="col-lg-12">
        <button id="addBtn" class="btn btn-lg add">Add New Policy</button>
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InsuredName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Expiration)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PolicyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InsuredName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Expiration)
            </td>
        </tr>
    }

</table>

<div id='addPolicyFormModal'>
</div>

PolicyWebsite/Views/InsurancePolicy/Partial/_AddPolicy.cshtml
@model Website.PolicyWebsite.Models.AddPolicy

<div id="validationError"></div>

@using (Html.BeginForm("add", "InsurancePolicy", FormMethod.Post, new { Id = "addPolicyForm" }))
{
    <div id="smartwizard">
        <ul>
            <li><a href="#step-1">Policy Number<br /></a></li>
            <li><a href="#step-2">Start/End Dates<br /></a></li>
            <li><a href="#step-3">Policy Holder<br /></a></li>
            <li><a href="#step-4">Property Location<br /></a></li>
            <li><a href="#step-5">Property Details<br /></a></li>
        </ul>

        <div>
            <div id="step-1" class="">
                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.PolicyNumber)
                        @Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Policy Number", onfocus = "(this.type='number')", onblur = "(this.type='text')" } })
                    </div>
                </div>
            </div>
            <div id="step-2" class="">
                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.EffectiveDate)
                        <div id="start_date"></div>
                    </div>

                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.ExpireDate)
                        <div id="end_date"></div>
                    </div>
                </div>
            </div>
            <div id="step-3" class="">
                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.FirstName)
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name" } })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.LastName)
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.Street)
                        @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control", placeholder = "Street Address" } })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.City)
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", placeholder = "City" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.State)
                        @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control", placeholder = "State", maxlength = 2 } })

                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.Zip)
                        @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control", placeholder = "Zip", maxlength = 9 } })

                    </div>
                </div>

            </div>
            <div id="step-4" class="">
                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.BuildingStreet)
                        @Html.EditorFor(model => model.BuildingStreet, new { htmlAttributes = new { @class = "form-control", placeholder = "Building Address" } })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.BuildingCity)
                        @Html.EditorFor(model => model.BuildingCity, new { htmlAttributes = new { @class = "form-control", placeholder = "Building City" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.BuildingState)
                        @Html.EditorFor(model => model.BuildingState, new { htmlAttributes = new { @class = "form-control", placeholder = "Building State", maxlength = 2 } })
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.BuildingZip)
                        @Html.EditorFor(model => model.BuildingZip, new { htmlAttributes = new { @class = "form-control", placeholder = "Building Zip", maxlength = 9 } })
                    </div>
                </div>
            </div>
            <div id="step-5" class="">
                <div class="form-group row">
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.YearBuilt)
                        <div id="year_built"></div>
                    </div>
                    <div class="col-xs-6">
                        @Html.LabelFor(model => model.RiskConstruction)
                        @Html.DropDownListFor(model => model.SelectedRiskConstruction, Model.RiskConstruction, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@*@using (Html.BeginForm("add", "InsurancePolicy", FormMethod.Post, new { Id = "addPolicyForm" }))
    {
        <div>
            <div class="form-group row">
                <div class="col-xs-12">
                    <h4>Policy Info</h4>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-xs-4">
                    @Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Policy Number", onfocus = "(this.type='number')", onblur = "(this.type='text')" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Effective Date", onfocus = "(this.type='date')", onblur = "(this.type='text')" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.ExpireDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Expiry Date", onfocus = "(this.type='date')", onblur = "(this.type='text')" } })
                </div>
            </div>

            <div class="row form-group">
                <div class="col-xs-12">
                    <h4>Primary Insured</h4>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-xs-4">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control", placeholder = "Street Address" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", placeholder = "City" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control", placeholder = "State" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control", placeholder = "Zip" } })
                </div>
            </div>

            <div class="row form-group">
                <div class="col-xs-12">
                    <h4>Insured Risk</h4>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-xs-4">
                    @Html.EditorFor(model => model.YearBuilt, new { htmlAttributes = new { id = "test", @class = "form-control", placeholder = "Year Built", onfocus = "(this.type='date')", onblur = "(this.type='text')" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.BuildingStreet, new { htmlAttributes = new { @class = "form-control", placeholder = "Building Address" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.BuildingCity, new { htmlAttributes = new { @class = "form-control", placeholder = "Building City" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.BuildingState, new { htmlAttributes = new { @class = "form-control", placeholder = "Building State" } })
                </div>

                <div class="col-xs-4">
                    @Html.EditorFor(model => model.BuildingZip, new { htmlAttributes = new { @class = "form-control", placeholder = "Building Zip" } })
                </div>
            </div>

            <div class="row form-group">
                <div class="col-xs-4">
                    @Html.DropDownListFor(model => model.SelectedRiskConstruction, Model.RiskConstruction, new { @class = "form-control" })
                </div>
            </div>
        </div>
    }*@

PolicyWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Policy Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/smartwizard")
    <!-- polyfiller file to detect and load polyfills -->
    <script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
    <script>
        webshims.setOptions('waitReady', false);
        webshims.setOptions('forms-ext', { types: 'date' });
        webshims.polyfill('forms forms-ext');
    </script>


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Policy Manager", "Index", "InsurancePolicy", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Policy Manager</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>